### ISSUE TITLE
Running ctdg finder after hmm screen on panther db on non-model species

### ISSUE THREAD

**Issue by evolgenomology** [biofilos/ctdg_finder#4]
Hi!

Now I have some general usage questions. I rand the preprocessing pipeline as we discussed in the issues #2 and #3 (this just for others to follow up if errors occur). Now I wanted to run the actual ctdg finder. I am ran the preprocessing on a divergent (non-model) genome, nice assembly though with several scaffolds in the Mb range of size, with the panther db as target. That is I copied the panther hmm file from Interproscan (should be latest panther) and screen all my ~16k proteins against it targeting scaffolds over 5kb in size. 
Firstly, I see that you have specific hmms for Ig, MHC, and zinc fingers in your test dataset. Do I similarly need to provide hmms for known gene families for my organism? In principle I could look for what is in there by looking at my interpro annotation. However, what I really want to know is, are there any CTDGs in this genome, regardless which family. It is a very interesting species, but nothing known about its biology. Everything is of interest. This question obviously also affects the command used to run the ctdg finder, because it asks for a family name.
Secondly, how could I use Pfams instead of hmms. This I think would be really helpful as Pfams seem more likely to pick up domains in divergent species than the PANTHER profiles, but I might be wrong.

Cheers

Philipp

**Comment by biofilos** [comment]
That is a very good question. CTDGFinder is agnostic in the kind of HMMs you want to include in your db. The only requirement is that they should be HMMer HMMs. I left the folder named panther/ for no real reason, and I might change its name to avoid confusion.
About Pfam, you can download the entire Pfam database as HMMer HMM from the Pfam ftp site.
About the genome assembly, I have some recommendations to make. First, keep in mind that every scaffold that you include in your `pre_chromosomes.csv` file, will be treated as a "chromosome". That is, the random sampling step of CTDGFinder will choose from any of those scaffolds. In our first paper, we show how that does not make much of a difference (we used the first draft from the human genome and the latest assembly at the time). However, if you have several hundred to thousands of scaffolds, chances are, most of them will have a few to no genes in them, or they will be sections with high density of genes (because CTDGs actually easy to sequence). For that reason, CTDGFinder could sample either "empty" chromosomes, or a "chromosome" sampled by it could contain only a CTDG. Those two things might skew the random distribution depending on your assembly. In order to avoid at least one of those undesired outcomes, I suggest that you remove scaffolds with less than a minimum of genes and under a length threshold. We used scaffolds with more than 10 genes and longer than 10kb for our latest paper, but we were working with mammals, which have more complete assemblies. At the very least, I would remove all scaffolds with less than 2 genes (the bare minimum of genes in a CTDG). Regarding the minimum "chromosome" length, that depends on the assembly you are working with

**Comment by evolgenomology** [comment]
Just shortly (more later) it was actually my reasoning to select scaffolds with at least two genes by setting my size threshold. I did not count though. Will do that now. 

P

⁣Sent from BlueMail ​

**Comment by evolgenomology** [comment]
Hi!

Could you also please comment on my question regarding the individual gene
hmms you used in the example? Are those needed?

Cheers

Philipp


On 18 February 2019 at 15:46:59, Juan Felipe Ortiz (notifications@github.com)
wrote:

That is a very good question. CTDGFinder is agnostic in the kind of HMMs
you want to include in your db. The only requirement is that they should be
HMMer HMMs. I left the folder named panther/ for no real reason, and I
might change its name to avoid confusion.
About Pfam, you can download the entire Pfam database as HMMer HMM from the
Pfam ftp site.
About the genome assembly, I have some recommendations to make. First, keep
in mind that every scaffold that you include in your pre_chromosomes.csv
file, will be treated as a "chromosome". That is, the random sampling
CTDGFinder will choose from any of those scaffolds. In our first paper, we
show how that does not make much of a difference (we used the first draft
from the human genome and the latest assembly at the time). However, if you
have several hundred scaffolds, chances are, most of them will have a few
to no genes in them, or they will be sections with high density of genes
(because CTDG actually easy to sequence). For that reason, CTDGFinder could
sample either "empty" chromosomes, or a "chromosome" sampled by it could
contain only a CTDG. Those two things might skew the random distribution
depending on your assembly. In order to avoid at least one of those
undesired outcomes, I suggest that you remove scaffolds with less than a
minimum of genes and under a length threshold. We used scaffolds with more
than 10 genes and longer than 10kb for our latest papr, but we were working
with mammals, which have more complete assemblies. At the very least, I
would remove all scaffolds with less than 2 genes (the bare minimum of
genes in a CTDG). Regarding the minimum "chromosome" length, that depends
on the assembly you are working with

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/biofilos/ctdg_finder/issues/4#issuecomment-464782919>,
or mute the thread

**Comment by biofilos** [comment]
No, those are sample hmms from pfam

**Comment by evolgenomology** [comment]
Thanks.


On 20 February 2019 at 16:03:30, Juan Felipe Ortiz (notifications@github.com)
wrote:

No, those are sample hmms from pfam

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/biofilos/ctdg_finder/issues/4#issuecomment-465640800>,
or mute the thread
